spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:zenjob
    username: zenjob
    password: challenge
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: create-drop
    open-in-view: false
  application:
    name: backend-challenge